# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 'Michael J. Decker, Ph.D.'
classtitle: 'Dr. Michael J. Decker'
email: 'mdecke@bgsu.edu'
affiliation: 'Department of Computer Science, Bowling Green State University'
office_building: 'Hayes Hall'
office_room: '242'
url: 'mjdecker.github.io'
homepage: 'mjdecker.github.io'
description: > # this means to ignore newlines until 'baseurl:'
  Website for Michael J. Decker, Ph.D.
baseurl: '' # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mjdecker

# Build settings
markdown: kramdown
theme: minima
highlighter: rouge

kramdown:
  smart_quotes: ['apos', 'apos', 'quot', 'quot']

collections:
  notes:
    output: true
  labs:
    output: true